# Generated by Django 5.0.6 on 2024-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='slidevideo')),
                ('caption', models.CharField(max_length=255)),
                ('sub_headding', models.CharField(max_length=255)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
