# Generated by Django 5.0.6 on 2024-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_job_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureSlids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.FileField(upload_to='picture')),
                ('caption', models.CharField(max_length=255)),
                ('sub_headding', models.CharField(max_length=255)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
