# Generated by Django 5.0.6 on 2024-09-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_pictureslids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_subname', models.CharField(max_length=255)),
                ('project_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('land_area', models.CharField(max_length=11)),
                ('bulding_area', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=100)),
                ('primary_image', models.FileField(upload_to='project_primary_image')),
                ('plan_image_1', models.FileField(upload_to='planimage')),
                ('plan_image_2', models.FileField(upload_to='planimage')),
                ('is_featured_product', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ProjectPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='project_images')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.projects')),
            ],
        ),
    ]
