# Generated by Django 5.0.6 on 2024-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_projects_alter_job_posted_on_projectpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_category',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('Residence', 'Residence'), ('Commercial', 'Commercial'), ('Office', 'Office'), ('Renovation', 'Renovation')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Completed', 'Completed')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
