# Generated by Django 5.0.6 on 2024-09-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_projects_project_category_projects_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
