# Generated by Django 5.0.6 on 2024-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_projects_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='galleryimages')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
