# Generated by Django 5.0.6 on 2024-09-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_galleryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='category',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Interior', 'Interior'), ('Ongoingworks', 'Ongoingworks'), ('Other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
