# Generated by Django 5.0.6 on 2024-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_galleryimages_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='testimonial_videos')),
                ('category', models.CharField(choices=[('Architecture', 'Architecture'), ('Interior', 'Interior'), ('Ongoingworks', 'Ongoingworks'), ('Other', 'Other')], default='Other', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
