# Generated by Django 5.0.6 on 2024-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
