# Generated by Django 5.1.2 on 2024-10-12 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_enquirys'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
