# Generated by Django 5.1.2 on 2024-10-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_enquirys'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
