# Generated by Django 5.2.4 on 2025-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureslids',
            name='sub_image',
            field=models.FileField(default=1, upload_to='picture/sub_image'),
            preserve_default=False,
        ),
    ]
