# Generated by Django 6.0 on 2025-12-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_medialibrary_menus_pages_menuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS for this page', null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='page_gallery_images', to='Home.medialibrary'),
        ),
        migrations.AddField(
            model_name='pages',
            name='gallery_videos',
            field=models.ManyToManyField(blank=True, related_name='page_gallery_videos', to='Home.medialibrary'),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_type',
            field=models.CharField(choices=[('standard', 'Standard Page'), ('gallery', 'Gallery Page'), ('project', 'Project Page')], default='standard', max_length=50),
        ),
    ]
