# Generated by Django 6.0 on 2025-12-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_pages_custom_css_pages_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibrary',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
