# Generated by Django 5.2.4 on 2025-12-24 04:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_medialibrary_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='bulding_area',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='location',
        ),
        migrations.AddField(
            model_name='projects',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='project_gallery_images', to='Home.medialibrary'),
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
