# Generated by Django 5.2.4 on 2025-12-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_remove_projects_bulding_area_remove_projects_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='plan_image_1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='plan_image_2',
        ),
    ]
