# Generated by Django 5.2.4 on 2025-12-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_remove_projects_plan_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_category',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Livelihood', 'Livelihood'), ('Environment', 'Environment'), ('Social Welfare', 'Social Welfare')], max_length=255),
        ),
    ]
