# Generated by Django 5.2.4 on 2025-12-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_services_menuitems_project_menuitems_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
