# Generated by Django 5.2.4 on 2025-12-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_projects_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='icon',
            field=models.CharField(blank=True, default='bi bi-flower1', help_text='Bootstrap Icon Class', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, default='bi bi-flower1', help_text='Bootstrap Icon Class', max_length=100, null=True),
        ),
    ]
