# Generated by Django 5.2.4 on 2025-12-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_projects_icon_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
