# Generated by Django 5.2.4 on 2025-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_projects_order_services_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ip_address', 'visit_date')},
            },
        ),
    ]
