# Generated by Django 5.2.7 on 2026-03-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0024_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_category",
            field=models.CharField(
                choices=[
                    ("Steel Fabrication", "Steel Fabrication"),
                    ("Structural Steel", "Structural Steel"),
                    ("Industrial Fabrication", "Industrial Fabrication"),
                    ("Fencing", "Fencing"),
                    ("Precast Concrete", "Precast Concrete"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
