# Generated by Django 5.2.7 on 2026-03-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0025_jobapplication_message_jobapplication_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimages",
            name="category",
            field=models.CharField(
                choices=[
                    ("Completed Projects Photos", "Completed Projects Photos"),
                    ("Approvals & Certifications", "Approvals & Certifications"),
                    ("Facility Photos", "Facility Photos"),
                    ("Team Photos", "Team Photos"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="testimonialvideos",
            name="category",
            field=models.CharField(
                choices=[
                    ("Completed Projects Photos", "Completed Projects Photos"),
                    ("Approvals & Certifications", "Approvals & Certifications"),
                    ("Facility Photos", "Facility Photos"),
                    ("Team Photos", "Team Photos"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
    ]
