# Generated by Django 6.0.1 on 2026-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0026_alter_galleryimages_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="project_category",
            field=models.CharField(
                choices=[
                    ("Villas", "Villas"),
                    ("Apartments", "Apartments"),
                    ("Land", "Land"),
                    ("Commercial", "Commercial"),
                    ("Shops", "Shops"),
                    ("Office Spaces", "Office Spaces"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
