# Generated by Django 6.0.1 on 2026-05-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0027_alter_projects_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=15, null=True
            ),
        ),
    ]
