# Generated by Django 6.0.1 on 2026-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0028_projects_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="purpose",
            field=models.CharField(
                choices=[("Sale", "For Sale"), ("Rent", "For Rent")],
                default="Sale",
                max_length=10,
            ),
        ),
    ]
