# Generated by Django 6.0.1 on 2026-05-25 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0031_projectamenity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pictureslids",
            name="linked_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slides",
                to="Home.projects",
            ),
        ),
        migrations.AddField(
            model_name="pictureslids",
            name="show_view_button",
            field=models.BooleanField(default=False),
        ),
    ]
