# Generated by Django 6.0.1 on 2026-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0032_pictureslids_linked_property_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
